### ISSUE TITLE
Implement contextualKeys for redis

### ISSUE THREAD

**Issue by hoangnd25** [sonata-project/cache#16]
Hi guys,

While it's possible to implement contextualKeys for redis (any key-value backend) by create a key - value for each context, i'm not sure if it's a bad approach.

For example:
Consider 2 objects

```
$post1 = array(
    'id' => array('blogId'=>1,'type'=>'view),
    'contexts' => array('authorId'=> 1,'imageId' => 2)
);
$post2 = array(
    'id' => array('blogId'=>2,'type'=>'view),
    'contexts' => array('authorId'=> 1,'imageId' => 3)
);
```

We could create 3 entries in redis for contextualKeys 

```
authorId1 => [post1,post2]
imageId2 => [post1]
imageId3 => [post2]
```

I created small js lib follow this approach, i'm not sure if this approach is bad
https://github.com/hoangnd25/cacheJS

**Comment by Soullivaneuh** [comment]
Hi @hoangnd25,

Feel free to make a PR for your proposition. :+1:
