### ISSUE TITLE
Make it PSR-6 compliant

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/cache#50]
Ref: http://www.php-fig.org/psr/psr-6/

Wait #49 before working on it.

**Comment by greg0ire** [comment]
1. Implement PSR-6
2. Make all dependents depend on PSR-6 instead of directly sonata-project/cache
3. Abandon sonata-project/cache? Unless it has features that are unique to it?

**Comment by core23** [comment]
Never been that deep into this component, but AFAIK symfony has a [new cache component ](https://symfony.com/blog/new-in-symfony-3-1-cache-component) which would replace this repo. So we can abondon sonata cache.

**Comment by greg0ire** [comment]
Sonata [libs depending on cache](https://packagist.org/packages/sonata-project/cache/dependents) : block bundle, cache bundle, page bundle. Maybe we should also drop the cache bundle?

**Comment by greg0ire** [comment]
Not sure why block depends on it though : https://github.com/sonata-project/SonataBlockBundle/search?p=1&q=Cache&utf8=%E2%9C%93

**Comment by greg0ire** [comment]
Oh ok I found the dependency, it is here : https://github.com/sonata-project/SonataCacheBundle/blob/cf9cce6dd1207ddbf89e4ce5ce9192476d36d87d/DependencyInjection/Compiler/CacheCompilerPass.php#L30 (there is a dependency on service ids from the cache… bundle? so it should depend on the cache bundle, not on the cache library?).

**Comment by core23** [comment]
Making it PSR-6 compliant will help to deprecate this bundle #49 with a smooth upgrade path.

**Comment by dmaicher** [comment]
Going to have a look at this

**Comment by dmaicher** [comment]
We can close this one, right? I don't think there is a point in implementing this.

**Comment by jordisala1991** [comment]
Yep, no point on using sonata cache since there is the Symfony one.

**Comment by VincentLanglet** [comment]
I thought it was to help the migration (for instance for the page bundle)

**Comment by dmaicher** [comment]
In case we see it would help the migration on the PageBundle we can maybe consider re-opening it. But not sure about it.
