### ISSUE TITLE
ISP violations

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/cache#96]
Looking at the implementations of cache adapter show code smells revealing several ISP violations:

- https://github.com/sonata-project/SonataCacheBundle/blob/2.x/src/Adapter/SymfonyCache.php#L205-L224
- https://github.com/sonata-project/SonataCacheBundle/blob/2.x/src/Adapter/SsiCache.php#L51-L62

These methods should be extracted to separate interfaces, and implementing them should be optional.

Likewise, the `isContextual` method should be removed and replaced with a marker interface. https://github.com/sonata-project/SonataCacheBundle/blob/2.x/src/Adapter/SymfonyCache.php#L229-L232

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/cache/issues/49
